server:
  port: 8081
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/springboot?useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "thienle255@gmail.com"
    password: "ubqzzirlujffqucr"
    #    password: "ubqz zirl ujff qucr"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


openapi:
  service:
    api-docs: api-service
    server: http://localhost:8081
    title: API Service
    version: 1.0.0

cors:
  allowed-origins:
    - "http://localhost:3000"
  allowed-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "PATCH"
  allowed-headers:
    - "*"
  allow-credentials: true